version: "1.0"


services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    env_file:
      - .env
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - ./psql_seedfile.txt:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "8081:5432"

  frontend:
    build:
     context: frontend/.
     dockerfile: Dockerfile
    ports:
     - "8082:443"
    volumes:
      - ./nginx-selfsingned.key:/etc/ssl/private/nginx-selfsigned.key:ro
      - ./nginx-selfsigned.pem:/etc/ssl/certs/nginx-selfsigned.pem:ro

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    
