server {
    listen 443 ssl default_server;
    
    listen [::]:443 ssl default_server;

    root /var/www/html;

    index index.html;

    server_name _;
    
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        index login.html;
	    try_files $uri $uri/ /login.html;
    }
    
    location /registration {
        try_files $uri $uri/ /register.html;
    }

    location /dashboard {
        auth_request /api/verify;

        try_files $uri $uri/ /dashboard.html;
    }

    location = /api/verify {
        proxy_pass http://auth:8000;
        proxy_set_header Content-Length "";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_origin;

    }

    location = /auth {
        proxy_pass http://auth:8000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Origin $http_origin;
    }

    location = /register {
        proxy_pass http://auth:8000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Origin $http_origin;
    }

    location ~ /\.ht {
        deny all;
    }
}